### ISSUE TITLE
UnityException error

### ISSUE THREAD

**Issue by TNoStone** [AdvizeGH/Advize_ValheimMods#6] opened 2023-03-01 17:07 UTC
when in development build i get this error:

'''UnityException: LoadFromStreamInternal is not allowed to be called from a MonoBehaviour constructor (or instance field initializer), call it in Awake or Start instead. Called from MonoBehaviour 'PlantEverything' on game object 'BepInEx_Manager'.
See "Script Serialization" page in the Unity Manual for further details.
  at (wrapper managed-to-native) UnityEngine.AssetBundle.LoadFromStreamInternal(System.IO.Stream,uint,uint)
  at UnityEngine.AssetBundle.LoadFromStream (System.IO.Stream stream) [0x00008] in <a4051268d5f04a0f9ae9868a690f7cdb>:0 
  at Advize_PlantEverything.PlantEverything.LoadAssetBundle (System.String fileName) [0x00015] in <c6610004fe6c4af8b246e00b16cfe861>:0 
  at Advize_PlantEverything.PlantEverything..cctor () [0x00047] in <c6610004fe6c4af8b246e00b16cfe861>:0 
Rethrow as TypeInitializationException: The type initializer for 'Advize_PlantEverything.PlantEverything' threw an exception.'''

and it causes configurationmanager to break

**Comment by AdvizeGH** [comment] 2023-03-04 02:04
Duplicate of #5 and PR has been merged, but the fix has yet to make it to public release.

**Closed by AdvizeGH** 2023-03-04 02:04 UTC
